name: tfsec with JSON report

on:
    push:
        branches: [ "main"]
    pull_request:
        branches: [ "main"]

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout external Terraform repo
        uses: actions/checkout@v3
        with:
          repository: terraform-aws-modules/terraform-aws-vpc
          path: terraform-code

      - name: Install tfsec
        run: |
            curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | sudo bash

      - name: Run tfsec with JSON output
        run: |
            mkdir -p reports
            tfsec terraform-code --format json --out reports/tfsec-report.json

    #   - name: Upload report as artifact
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: tfsec-report
    #       path: tfsec-report.json

      - name: Commit and push report
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reports/tfsec-report.json
          git commit -m "Add tfsec scan report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}