name: Trivy Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Scan Docker image and Terraform IaC with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Date
        id: set-date
        run: echo "DATE=$(date +%m.%d.%Y)" >> $GITHUB_ENV

      - name: Create output directory
        run: mkdir -p "GitHubActions/Trivy Automation"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Download Trivy vulnerability DB
        run: trivy image --download-db-only

      - name: Run Trivy vulnerability scan on Docker image
        run: |
          OUTPUT_FILE="GitHubActions/Trivy Automation/trivy_report_${{ env.DATE }}.json"
          trivy image --format json --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM,LOW -o "$OUTPUT_FILE" cloudhack01/vulnapp:latest

      - name: Run Trivy IaC scan (Terraform)
        run: |
          IAC_OUTPUT_FILE="GitHubActions/Trivy Automation/trivy_iac_report_${{ env.DATE }}.json"
          trivy config --format json -o "$IAC_OUTPUT_FILE" .

      - name: Scan remote Terraform repository
        run: |
          git clone https://github.com/claranet/terraform-azurerm-run-iaas.git temp-repo
          cd temp-repo
          IAC_REMOTE_OUTPUT_FILE="../GitHubActions/Trivy Automation/trivy_remote_tf_report_${{ env.DATE }}.json"
          trivy config --format json -o "$IAC_REMOTE_OUTPUT_FILE" .
          cd ..
          rm -rf temp-repo

      - name: Verify scan results exist
        run: ls -l "GitHubActions/Trivy Automation/"

      - name: Commit scan results to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "RafaelView"
          git config --global user.email ""
          git add "GitHubActions/Trivy Automation/trivy_report_${{ env.DATE }}.json"
          git add "GitHubActions/Trivy Automation/trivy_iac_report_${{ env.DATE }}.json"
          git add "GitHubActions/Trivy Automation/trivy_remote_tf_report_${{ env.DATE }}.json"
          git commit -m "Add Trivy scan reports (Docker + IaC + Remote Terraform) for ${{ env.DATE }}"
          git push origin HEAD:main
