name: build
on:
  push:
    branches:
      - main
  pull_request:

    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Terraform repository
        run: |
          git clone https://github.com/alibaba/terraform-provider.git temp-repo

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'json' # Cambiado a JSON
          output: 'trivy-results.json' # Archivo de salida en formato JSON
          input: './temp-repo'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_SEVERITY: 'CRITICAL,HIGH'
          TRIVY_IACT_MODE: 'true'
          TRIVY_IACT_CONFIG: 'true'
          TRIVY_IACT_VULN: 'false'
          TRIVY_IACT_POLICY: 'false'

      - name: Commit and push Trivy scan results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "RafaelView"
          git config --global user.email "rafael.jimenezb@viewnext.com"
          git add trivy-results.json
          git commit -m "Add Trivy scan results in JSON format"
          git push origin HEAD:main