name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Terraform repository
        run: |
          git clone https://github.com/alibaba/terraform-provider.git temp-repo

      - name: Set current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create directory for Trivy reports
        run: mkdir -p "Trivy Reports"

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'json'
          output: "Trivy Reports/trivy_report_${{ env.CURRENT_DATE }}.json"
          input: './temp-repo'
          exit-code: '0'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL' # Escanea todas las severidades
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_SEVERITY: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          TRIVY_IACT_MODE: 'true'
          TRIVY_IACT_CONFIG: 'true'
          TRIVY_IACT_VULN: 'false'
          TRIVY_IACT_POLICY: 'false'

      - name: Commit and push Trivy scan results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "RafaelView"
          git config --global user.email "rafael.jimenezb@viewnext.com"
          git add "Trivy Reports/trivy_report_${{ env.CURRENT_DATE }}.json"
          git commit -m "Add Trivy scan results for ${{ env.CURRENT_DATE }}"
          git push origin HEAD:main